### ISSUE TITLE
Looking for 2020 website

### ISSUE THREAD

**Issue by ricoms** [zalandoresearch/fashionxrecsys#6]
Hello.

I was looking for the 2020 edition website to send a PR to correct my affiliation. Also, there are some minor HTML bugs, that I could help with.

If you see fit I volunteer myself for help.

Best regards,
Ricardo.

**Comment by hcorona-zz** [comment]
Hi Ricardo,
Apologies for the typos, your PR would be very welcomed :) I'll review it as soon as I get it!

**Comment by ricoms** [comment]
no need for apologies
